// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2NGG0Vd3TZptSKMIXxD8a9lL5nG3cNuw',
    appId: '1:770687374485:web:10d29a5c253150b1e2b79c',
    messagingSenderId: '770687374485',
    projectId: 'guidetouristiquelocal',
    authDomain: 'guidetouristiquelocal.firebaseapp.com',
    storageBucket: 'guidetouristiquelocal.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBv-1oBP3J2VUpYMWTKNqYcafglyiHBLiU',
    appId: '1:770687374485:android:68c2024d396de79be2b79c',
    messagingSenderId: '770687374485',
    projectId: 'guidetouristiquelocal',
    storageBucket: 'guidetouristiquelocal.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAg_1K111UQP2AfOTIVPzoz4kiNPh0AnUA',
    appId: '1:770687374485:ios:0e49b371c06914cae2b79c',
    messagingSenderId: '770687374485',
    projectId: 'guidetouristiquelocal',
    storageBucket: 'guidetouristiquelocal.firebasestorage.app',
    iosClientId: '770687374485-qng6a90ha560lnlhjqod0kkqphp3qf9b.apps.googleusercontent.com',
    iosBundleId: 'com.example.guideTouristiqueLocal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAg_1K111UQP2AfOTIVPzoz4kiNPh0AnUA',
    appId: '1:770687374485:ios:0e49b371c06914cae2b79c',
    messagingSenderId: '770687374485',
    projectId: 'guidetouristiquelocal',
    storageBucket: 'guidetouristiquelocal.firebasestorage.app',
    iosClientId: '770687374485-qng6a90ha560lnlhjqod0kkqphp3qf9b.apps.googleusercontent.com',
    iosBundleId: 'com.example.guideTouristiqueLocal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2NGG0Vd3TZptSKMIXxD8a9lL5nG3cNuw',
    appId: '1:770687374485:web:3dc56fb1a14271aae2b79c',
    messagingSenderId: '770687374485',
    projectId: 'guidetouristiquelocal',
    authDomain: 'guidetouristiquelocal.firebaseapp.com',
    storageBucket: 'guidetouristiquelocal.firebasestorage.app',
  );
}
